package org.example;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.example.model.Patient;

import javax.swing.*;
import java.awt.*;
import java.util.List;

public class PatientLookUp extends JFrame {

    private JPanel contentPane;
    private JList<String> rooms;
    private JButton searchButton;
    private JTextField input;
    private JLabel patientLabel;

    private final ApiService apiService = new ApiService();

    public PatientLookUp() {
        setTitle("Hospital Maternity Unit");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setContentPane(contentPane);
        pack();
        setLocationRelativeTo(null);

        // listen for click on search button, changed to lambda (suggested by intelliJ)
        searchButton.addActionListener(_ -> handleSearch());

        // display frame
        setVisible(true);
    }

    private void handleSearch() {
        String text = input.getText().trim(); // get input and remove blank spaces

        // catch empty input
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a patient ID.");
            patientLabel.setText("");
            rooms.setModel(new DefaultListModel<>());
            return;
        }

        int patientId;
        try {
            patientId = Integer.parseInt(text); // convert text to integer and assign to patient id
            // catch inputs that are not an integer
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a positive number.");
            input.setText("");
            patientLabel.setText("");
            rooms.setModel(new DefaultListModel<>());
            return;
        }

        // catch negative values
        if (patientId < 1) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a positive number.");
            input.setText("");
            patientLabel.setText("");
            rooms.setModel(new DefaultListModel<>());
            return;
        }

        try {
            // get patient from external api
            Patient patient = apiService.getPatient(patientId);

            // stop and return without calling local api if patient doesn't exist
            if (patient == null) {
                JOptionPane.showMessageDialog(this, "No patient with ID " + patientId + ".");
                input.setText("");
                patientLabel.setText("");
                rooms.setModel(new DefaultListModel<>());
                return;
            }

            // get the local F1 api endpoint
            List<Integer> roomList = apiService.getRoomsByPatient(patientId);

            // clear input
            input.setText("");

            DefaultListModel<String> model = new DefaultListModel<>();
            // display no rooms for patient found message instead of empty list -> tells user what is wrong
            if (roomList.isEmpty()) {
                model.addElement("No rooms found.");
            } else {
                // put rooms from response array into list
                for (Integer roomId : roomList) {
                    model.addElement("Room: " + roomId);
                }
            }
            patientLabel.setText("Patient: " + patient.forename + " " + patient.surname);
            rooms.setModel(model); // return the list of rooms

            // catch api connection error (e.g. part A is not running)
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Could not connect to local server.",
                    "Connection Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(6, 3, new Insets(10, 10, 10, 10), -1, -1));
        contentPane.setPreferredSize(new Dimension(400, 200));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(3, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        rooms = new JList();
        contentPane.add(rooms, new GridConstraints(3, 2, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Look up a Patient ID");
        contentPane.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(60, 23), null, 0, false));
        searchButton = new JButton();
        searchButton.setText("Search");
        contentPane.add(searchButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setEnabled(true);
        label2.setText("<html><b>Patient Room Look Up</b></html>");
        contentPane.add(label2, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("List of Rooms");
        contentPane.add(label3, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(84, 23), null, 0, false));
        patientLabel = new JLabel();
        patientLabel.setText("Patient Name");
        contentPane.add(patientLabel, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        input = new JTextField();
        input.setText("");
        contentPane.add(input, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 30), new Dimension(150, 30), new Dimension(250, 30), 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}